# A sample Gemfile
source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "memcache-client"
gem "foreman"
gem "unicorn"
gem "mysql2"
gem "rack-flash3"

group :development do
  gem 'rack-lineprof'
  gem 'rack-mini-profiler'
  gem 'stackprof'

  # For memory profiling (requires Ruby MRI 2.1+)
  gem 'memory_profiler'

  # For call-stack profiling flamegraphs (requires Ruby MRI 2.0.0+)
  gem 'flamegraph'
  gem 'stackprof'     # For Ruby MRI 2.1+
  gem 'fast_stack'    # For Ruby MRI 2.0
end
